### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by JsBergbau** [hargoniX/keepassxc-proxy-client#2]
Hi @hargoniX 
thanks for this great piece of code, especially because it is well documented.

I've tried to use it with windows, but sadly there is no support yet. So I've tried a bit to integrate with a little bit help from another repository. But this is badly documented and didn't work for me. So I'd like to use your code.

When trying to execute the example code without any changes this error occurs
```
self.socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: module 'socket' has no attribute 'AF_UNIX'
```
So basically it tries to establish a UNIX socket. 

So I've tried to give it Windows support.

I've tried to adopt code from here https://github.com/hrehfeld/python-keepassxc-browser/blob/master/keepassxc_browser/connection_win.py

by making changes to protocol.py

```
if platform.system() == "Windows":
    import win32file
    import getpass
```
adding changed code from link above
```
class WinSock:
    """ A basic socket wrapper for Windows named pipes """

    def __init__(self, desired_access, creation_disposition, share_mode=0,
                 security_attributes=None, flags_and_attributes=0, input_nullok=None):
        self.desired_access = desired_access
        self.creation_disposition = creation_disposition
        self.share_mode = share_mode
        self.security_attributes = security_attributes
        self.flags_and_attributes = flags_and_attributes
        self.input_nullok = input_nullok
        self.handle = None

    def connect(self, address):
        try:
            self.handle = win32file.CreateFile(
                r'\\.\pipe\%s' % address,
                self.desired_access,
                self.share_mode,
                self.security_attributes,
                self.creation_disposition,
                self.flags_and_attributes,
                self.input_nullok
            )
        except Exception as e:
            raise Exception(
                "Could not connect to pipe {addr}".format(addr=address), e
            )

    def close(self):
        if self.handle:
            self.handle.close()

    def sendall(self, message):
        win32file.WriteFile(self.handle, message)

    def recv(self, buff_size):
        response_code, data = win32file.ReadFile(self.handle, buff_size)
        #return data, response_code
        return data
```
in __init__
```
if platform.system() == "Windows":
            self.socket = WinSock(win32file.GENERIC_READ | win32file.GENERIC_WRITE, win32file.OPEN_EXISTING)
        else:
            self.socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
```
changed get_socket_path
```
    def get_socket_path():
        server_name = "/org.keepassxc.KeePassXC.BrowserServer"
        system = platform.system()
        if system == "Linux" and "XDG_RUNTIME_DIR" in os.environ:
            return os.environ["XDG_RUNTIME_DIR"] + server_name
        elif system == "Windows":
            pathWin = "org.keepassxc.KeePassXC.BrowserServer_"  + getpass.getuser()
            return pathWin
        else:
            return "/tmp" + server_name
```

Now I get
```
Traceback (most recent call last):
  File "c:/testskript/KeepassXCSchnittstellentest.py", line 12, in <module>
    name, public_key = connection.dump_associate()
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\keepassxc_proxy_client\protocol.py", line 133, in dump_associate
    return (self.associate_id, self.id_public_key._public_key)
AttributeError: 'Connection' object has no attribute 'associate_id'
```

Would be very nice if you could take a look to give it Windows support.

**Comment by hargoniX** [comment]
Hey. So first things first I don't really have a Windows machine I use keepassxc on so I would have no way to really test myself at the moment.

That being said I would be happy to help you making a PR to this project. The attribute `associated_id` gets set if you call either `associate()` or `load_associate()` on a connection object, does your script do that? And would you be willing to share it as a whole so I can maybe do some debugging on my Linux as well?

**Comment by JsBergbau** [comment]
Hi hargniX,

thanks for your fast support and helping to support it on windows.

I used the second code example when I got this error so:
```
connection = keepassxc_proxy_client.protocol.Connection()
connection.connect()

name, public_key = connection.dump_associate()
# save it and read it in again for later

print("Name",name)
print("public",public_key)
```
So after your answer this should be 
```
connection = keepassxc_proxy_client.protocol.Connection()
connection.connect()
connection.associate()
name, public_key = connection.dump_associate()
# save it and read it in again for later

print("Name",name)
print("public_key",public_key)
```
Then a Keepass Dialog shows where I can enter the name of the connection and I get a public key.

Then I can load it
```
connection = keepassxc_proxy_client.protocol.Connection()
connection.connect()
connection.load_associate("test2", b'<Kestring>')
print(connection.test_associate())
```
and it returns true.

However trying to get `print(connection.get_logins("example.org"))` it returns
```
keepassxc_proxy_client.protocol.ResponseUnsuccesfulException: {'action': 'get-logins', 'error': 'Keine Anmeldedaten gefunden', 'errorCode': '15'}
```
Basically I save all my logins without http or https because in Browser sometimes you're on the URL with www, sometimes without, so both work this way.
When I request a login for the first time on Browser a Keepass dialog is shown where I can confirm the login and also remember that I shared this login. It seems like there is missing a trigger for this dialog. Since I use Keepass in German and in your code is no string "Keine Anmeldedaten gefunden" it looks like the connection is successfully working.

PS:
Only Browserintegration has to be enabled to use keepassxc-proxy.client. Even if all Browsers are unchecked it works, contrary to Keepass in Browser.
![grafik](https://user-images.githubusercontent.com/37013344/116354758-27b80a00-a7f9-11eb-8bea-e06d7b97c0fd.png)

If Browserintegration is disabled you get this error on Windows
```
Exception: ('Could not connect to pipe org.keepassxc.KeePassXC.BrowserServer_username', error(231, 'CreateFile', 'Alle Pipeinstanzen sind ausgelastet.'))
```

**Comment by hargoniX** [comment]
Ok so basically when you actually perform the association works and the issue is rather that you don't have the proper URL saved to access right? Originally when i built this tool it was meant as a mean to easily connect my `mutt(1)` email client to my keepassxc instance so I don't always have to copy passwords around so really it's not meant as a CLI wrapper around keepass (in fact keepass already has a CLI tool `keepassxc-cli` for interactive usage if you are searching for that). So I wouldn't say triggering this dialog is in the scope of the tool, at least not at the moment.

That being said, since your connection seems to be working just fine for now it would be very cool if you would PR your windows specific changes + maybe a change to the second example I seem to have messed up!

Note after checking out the other repo: It seems their Code is under a GPLv3 license while mine is a BSD zero clause so it would actually be illegal to just takeover their code into this project :/

**Comment by JsBergbau** [comment]
> Ok so basically when you actually perform the association works and the issue is rather that you don't have the proper URL saved to access right?

I have saved an entry with URL "example.org" if you mean that. 
I'm missing this dialog
![grafik](https://user-images.githubusercontent.com/37013344/116367436-a5831200-a807-11eb-9912-adbc1bb4e6b8.png)

> Originally when i built this tool it was meant as a mean to easily connect my mutt(1) email client to my keepassxc instance so I don't always have to copy passwords around

So how did you get Keepass to accept that request?

I didn't know Keepass CLI so far. However I knew that there are other Python Keepass implementations which directly open the database. That's not what I'm looking for. My usecase: I open Keepass for usage with browser. However I have also some automation scripts. These scripts should now connect to the already open KeepassXC and get their passwort from there, so it isn't stored inside the scripts.

> Note after checking out the other repo: It seems their Code is under a GPLv3 license while mine is a BSD zero clause so it would actually be illegal to just takeover their code into this project :/

So what do you recommend about this? I'm not a license expert.

**Comment by hargoniX** [comment]
So regarding the dialog, that one does show up for me so this is presumably a windows specific issue :/ and I'm not too familiar with the keepasxc code base myself either so I'm afraid I won't be of much help figuring out why it doesnt show up for you.

And regarding the license part, I'm not quite sure, I just know that project like OpenBSD that run under a BSD license strictly forbid copying code thats under GNU GPL, you'd basically have to come up with your own implementation.

**Comment by JsBergbau** [comment]
Ok now I've figured it out.
It is ok to save it as `example.org`
![grafik](https://user-images.githubusercontent.com/37013344/116389830-b2aafb80-a81d-11eb-9326-4de8513e05f5.png)

However when retrieving login-code you have to use
```
print(connection.get_logins("https://example.org"))
or
print(connection.get_logins("https://example.org"))
even this works:
print(connection.get_logins("https://www.example.org"))
```
also http:// instead of https:// works

**Comment by JsBergbau** [comment]
Pullrequest has been created.

**Comment by hargoniX** [comment]
https://pypi.org/project/keepassxc-proxy-client/0.1.4/ version with windows support published here
